//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDatabaseFirstAgain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyGameDatabaseEntities : DbContext
    {
        public MyGameDatabaseEntities()
            : base("name=MyGameDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ConsoleGames> ConsoleGames { get; set; }
        public virtual DbSet<DownloadContents> DownloadContents { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<Plataforms> Plataforms { get; set; }
        public virtual DbSet<Progress> Progress { get; set; }
    }
}
