//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDatabaseFirstAgain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public System.Guid Id { get; set; }
        public float Percentual { get; set; }
        public System.DateTime JogadoEm { get; set; }
        public Nullable<System.Guid> Jogador_JogadorId { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
