// <auto-generated />
namespace ConsoleCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class PassagemParaIngles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PassagemParaIngles));
        
        string IMigrationMetadata.Id
        {
            get { return "202111131252203_PassagemParaIngles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
