// <auto-generated />
namespace ConsoleCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class ADicionadaPropriedadeNaoMapeada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADicionadaPropriedadeNaoMapeada));
        
        string IMigrationMetadata.Id
        {
            get { return "202111162006532_ADicionadaPropriedadeNaoMapeada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
